theme: jekyll-theme-hacker
title: Ramashish Gaurav's Blog
email:
description: "A place where I share my findings with you!"
baseurl: ""
url: "http://r-gaurav.github.io"
github_username:  r-gaurav

comments: true
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-r-gaurav-github-io
