theme: jekyll-theme-hacker
title: Ramashish Gaurav's Blog
email:
description: "A place where I share my findings with you!"
baseurl: ""
url: "http://r-gaurav.github.io"
github_username:  r-gaurav
disqus_shortname: https-r-gaurav-github-io
